### PR TITLE
Add generic git commands to git-tui command

### PR DESCRIPTION
**Pull request by lu-maca**
Hi, with this change you will be able to run all git commands by using git-tui. For example:

immagine

immagine

### CODE REVIEW

**Comment by ArthurSonzogni** [comment]
Thanks!
I think I will merge something like this, but not using `std::system`. I will take a look.

**Comment by lu-maca** [comment]
@ArthurSonzogni thanks :)
What's the main point of using `std::subprocess` as done in diff and log instead of `std::system`?

**Comment by ArthurSonzogni** [comment]
> What's the main point of using std::subprocess as done in diff and log instead of std::system?

I would like to plumb directly `argv` and `argc`.
Some arguments might contains some space, causing std::system issues to interpret the command.

When using sh to execute the command, it removed the `""` and/or unescaped them. You would have to apply a similar escape when using std::system for the command to be interpreted correctly.

**Comment by lu-maca** [comment]
Hi @ArthurSonzogni, I've added `subprocess::run` to process generic commands, as you suggested

**Comment by ArthurSonzogni** [comment]
Thank you!

**Comment by lu-maca** [comment]
Thank you :) will  there be a release?

**Comment by ArthurSonzogni** [comment]
It already happened: v1.2.0
🎉

**Pull request merged**
